version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
      - echo Preparing the vendor
  build:
    commands:
      - echo Build started on `date`
      - echo Building the binary
  post_build:
    commands:
        - echo Build completed on `date`
        - echo Pushing the Docker image...
        - echo Writing image definitions file...
